# Generated by Django 3.2.16 on 2022-10-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('shortened_url', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
