# Generated by Django 3.2.16 on 2022-10-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortened_url',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
