# Generated by Django 3.2.16 on 2022-10-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_shortened_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
