# Generated by Django 3.2.16 on 2022-10-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_url_shortened_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortened_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
