version: "3.3"

services:

  db:
    image: postgres
    container_name: db
    hostname: db
    restart: unless-stopped
    ports:
      - "54325:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app-network

  api:
    build:
      context: ../
      dockerfile: ./stack/backend/Dockerfile
    container_name: api
    hostname: api
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ../backend/urlshortener:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  web:
    build:
      context: ../
      dockerfile: ./stack/frontend/Dockerfile
    container_name: web
    hostname: web
    restart: unless-stopped
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge